//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUDITORIA
    {
        public int ID_auditoria { get; set; }
        public string entidad_modificada { get; set; }
        public System.DateTime fecha_hora { get; set; }
        public string valor_nuevo { get; set; }
        public string valor_anterior { get; set; }
        public int dni_usuario { get; set; }
        public int ID_accion { get; set; }
    
        public virtual ACCION ACCION { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
