//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENTE()
        {
            this.CUENTA_CORRIENTE = new HashSet<CUENTA_CORRIENTE>();
            this.PEDIDO = new HashSet<PEDIDO>();
        }
    
        public int ID_cliente { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public int dni { get; set; }
        public int telefono { get; set; }
        public string email { get; set; }
        public string ciudad { get; set; }
        public string provincia { get; set; }
        public string calle { get; set; }
        public int numero { get; set; }
        public int cod_postal { get; set; }
        public System.DateTime fecha_alta { get; set; }
        public bool estado { get; set; }
        public string razon_social { get; set; }
        public string condicion_frenteIVA { get; set; }
        public int cuil_cuit { get; set; }
        public int ID_zona { get; set; }
        public int ID_tamano { get; set; }
        public int preventista { get; set; }
    
        public virtual TAMAÑO_NEGOCIO TAMAÑO_NEGOCIO { get; set; }
        public virtual ZONA ZONA { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUENTA_CORRIENTE> CUENTA_CORRIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PEDIDO> PEDIDO { get; set; }
    }
}
