//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PAGO()
        {
            this.PEDIDO = new HashSet<PEDIDO>();
        }
    
        public int ID_pago { get; set; }
        public decimal monto { get; set; }
        public System.DateTime fecha { get; set; }
        public string motivo_rechazo { get; set; }
        public int ID_estado { get; set; }
        public int ID_metodo { get; set; }
    
        public virtual ESTADO_PAGO ESTADO_PAGO { get; set; }
        public virtual METODO_PAGO METODO_PAGO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PEDIDO> PEDIDO { get; set; }
    }
}
