//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUENTA_CORRIENTE
    {
        public decimal saldo_actual { get; set; }
        public System.DateTime fecha_ultimo_movimiento { get; set; }
        public int id_cliente { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
    }
}
