//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_compra
    {
        public int compra_id { get; set; }
        public int detalle_compra_id { get; set; }
        public int cantidad_bulto { get; set; }
        public decimal precio_unitario { get; set; }
        public int id_producto { get; set; }
        public int ID_presentacion { get; set; }
    
        public virtual compra compra { get; set; }
        public virtual producto_presentacion producto_presentacion { get; set; }
    }
}
