//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_PEDIDO
    {
        public int cantidad { get; set; }
        public decimal descuento { get; set; }
        public int ID_detalle_pedido { get; set; }
        public int id_pedido { get; set; }
        public int id_producto { get; set; }
        public int ID_presentacion { get; set; }
    
        public virtual PEDIDO PEDIDO { get; set; }
        public virtual producto_presentacion producto_presentacion { get; set; }
    }
}
