//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedido_pago
    {
        public int id_pedido { get; set; }
        public int id_pago { get; set; }
        public decimal saldo { get; set; }
    
        public virtual PAGO PAGO { get; set; }
        public virtual PEDIDO PEDIDO { get; set; }
    }
}
