//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTO()
        {
            this.producto_presentacion = new HashSet<producto_presentacion>();
        }
    
        public int id_producto { get; set; }
        public string nombre { get; set; }
        public decimal precioLista { get; set; }
        public int stockActual { get; set; }
        public int umbralStock { get; set; }
        public int unidadesBulto { get; set; }
        public bool activo { get; set; }
        public int id_familia { get; set; }
        public int id_marca { get; set; }
    
        public virtual FAMILIA FAMILIA { get; set; }
        public virtual MARCA MARCA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<producto_presentacion> producto_presentacion { get; set; }
    }
}
