//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock
    {
        public int stock_id { get; set; }
        public int stock_actual { get; set; }
        public int umbral_stock { get; set; }
        public int id_producto { get; set; }
        public int ID_presentacion { get; set; }
    
        public virtual producto_presentacion producto_presentacion { get; set; }
    }
}
